const builderPlans = [
  { id:'reservoir', icon:'💧', title:'Tungabhadra Reservoir', text:'Store water for homes, fields, and seasonal uncertainty.', cost:{food:2}, reward:{water:3,prosperity:10}, lesson:'Waterworks turned a river landscape into a resilient city.' },
  { id:'market', icon:'🧺', title:'Bazaar Street', text:'Give farmers, craftspeople, and visitors a place to exchange ideas and goods.', cost:{water:2}, reward:{food:3,prosperity:12}, lesson:'Markets connected Hampi to regional and overseas trade.' },
  { id:'workshop', icon:'🔨', title:'Artisan Workshop', text:'Support skilled builders and makers who turn resources into culture.', cost:{food:3,water:1}, reward:{culture:2,prosperity:15}, lesson:'A great city relies on skilled communities, not stone alone.' },
  { id:'temple', icon:'🛕', title:'Festival Temple', text:'Create a shared place for ritual, music, and community gathering.', cost:{food:2,water:2,culture:3}, reward:{prosperity:25}, lesson:'Architecture can bring art, belief, and public life together.' }
];
const timelineEvents = [
  { id:'indus', symbol:'◫', title:'Indus Valley cities flourish', date:'c. 2600 BCE', order:0 },
  { id:'ashoka', symbol:'☸', title:'Ashoka’s reign and edicts', date:'3rd century BCE', order:1 },
  { id:'ajanta', symbol:'◒', title:'Ajanta cave art develops', date:'2nd century BCE onward', order:2 },
  { id:'hampi', symbol:'♜', title:'Vijayanagara flourishes at Hampi', date:'14th–16th century CE', order:3 },
  { id:'taj', symbol:'✦', title:'Taj Mahal is commissioned', date:'17th century CE', order:4 }
];
const memoryPairs = [
  { key:'taj', symbol:'✦', label:'Taj Mahal' }, { key:'hampi', symbol:'♜', label:'Hampi' }, { key:'konark', symbol:'☀', label:'Konark Sun Temple' },
  { key:'sanchi', symbol:'☸', label:'Sanchi Stupa' }, { key:'ajanta', symbol:'◒', label:'Ajanta Caves' }, { key:'charminar', symbol:'⌂', label:'Charminar' }
];
const state = { city:{food:5,water:5,culture:2,prosperity:0,built:[]}, selectedTimeline:[], timelinePool:[], flipped:[], moves:0, pairs:0, locked:false, sound:true };
const $ = (id) => document.getElementById(id);
const feedback = (id,message,type='') => { const el=$(id); el.textContent=message; el.className=`game-feedback ${type}`; };
function playTone(type='tap') { if(!state.sound) return; try { const ctx=new (window.AudioContext||window.webkitAudioContext)(); const o=ctx.createOscillator(),g=ctx.createGain(); o.type='sine'; o.frequency.value=type==='good'?660:type==='bad'?180:420; g.gain.setValueAtTime(.045,ctx.currentTime); g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.14); o.connect(g).connect(ctx.destination); o.start(); o.stop(ctx.currentTime+.15); } catch (_) {} }
function recordWin(key) { const wins=JSON.parse(localStorage.getItem('echoesArcadeWins')||'[]'); if(!wins.includes(key)){wins.push(key); localStorage.setItem('echoesArcadeWins',JSON.stringify(wins));} $('gamesWon').textContent=wins.length; }
function renderWins(){ try{$('gamesWon').textContent=JSON.parse(localStorage.getItem('echoesArcadeWins')||'[]').length;}catch(_){$('gamesWon').textContent='0';} }
function resetBuilder(){ state.city={food:5,water:5,culture:2,prosperity:0,built:[]}; renderBuilder(); feedback('builderFeedback','Start with a reservoir: water helps every community thrive.'); }
function renderBuilder(){ const c=state.city; $('foodValue').textContent=c.food; $('waterValue').textContent=c.water; $('cultureValue').textContent=c.culture; $('prosperityValue').textContent=c.prosperity; $('builderMission').textContent=c.built.length===4?'City complete — your people have water, trade, skill, and a shared cultural centre.':`Mission: build all four landmarks. ${4-c.built.length} landmark${4-c.built.length===1?'':'s'} remain.`; $('buildGrid').innerHTML=builderPlans.map(plan=>{const built=c.built.includes(plan.id); const costText=Object.entries(plan.cost).map(([key,value])=>`${key==='food'?'🌾':key==='water'?'💧':'🪔'} ${value} ${key}`).join(' · '); return `<article class="build-card ${built?'built':''}"><div class="build-icon">${plan.icon}</div><h3>${plan.title}</h3><p>${plan.text}</p><p class="cost">COST: ${costText}</p><button class="build-btn" type="button" data-build="${plan.id}" ${built?'disabled':''}>${built?'✓ BUILT':'BUILD LANDMARK'}</button></article>`;}).join(''); document.querySelectorAll('[data-build]').forEach(btn=>btn.onclick=()=>buildCity(btn.dataset.build)); }
function buildCity(id){ const plan=builderPlans.find(item=>item.id===id),c=state.city; if(Object.entries(plan.cost).some(([key,value])=>c[key]<value)){ feedback('builderFeedback',`Not enough resources for ${plan.title}. Read the cost and choose the landmark that prepares the city first.`,'bad'); playTone('bad'); return; } Object.entries(plan.cost).forEach(([key,value])=>c[key]-=value); Object.entries(plan.reward).forEach(([key,value])=>c[key]+=value); c.built.push(id); renderBuilder(); const complete=c.built.length===builderPlans.length; feedback('builderFeedback',complete?`City complete! ${plan.lesson} You created ${c.prosperity} prosperity.`:`${plan.title} built. ${plan.lesson}`, 'good'); playTone('good'); if(complete) recordWin('builder'); }
function shuffle(list){ return [...list].sort(()=>Math.random()-.5); }
function resetTimeline(){ state.selectedTimeline=[]; state.timelinePool=shuffle(timelineEvents); renderTimeline(); feedback('timelineFeedback','Look for broad eras first: ancient cities come before empires and monuments.'); }
function renderTimeline(){ const selected=state.selectedTimeline; $('timelineCount').textContent=`${selected.length} / ${timelineEvents.length}`; $('eventBank').innerHTML=state.timelinePool.map(event=>`<button type="button" class="event-card" data-event="${event.id}" ${selected.some(item=>item.id===event.id)?'disabled':''}><span class="event-symbol">${event.symbol}</span><span><strong>${event.title}</strong><small>${event.date}</small></span></button>`).join(''); const trail=$('answerTrail'); trail.innerHTML=selected.length?selected.map(event=>`<li><strong>${event.title}</strong> <span>— ${event.date}</span></li>`).join(''):'<li class="trail-placeholder">Your selected events will appear here.</li>'; document.querySelectorAll('[data-event]').forEach(btn=>btn.onclick=()=>{const event=timelineEvents.find(item=>item.id===btn.dataset.event); state.selectedTimeline.push(event); renderTimeline(); playTone();}); }
function checkTimeline(){ if(state.selectedTimeline.length<timelineEvents.length){feedback('timelineFeedback','Choose every event before checking the trail.','bad');playTone('bad');return;} const correct=state.selectedTimeline.every((event,index)=>event.order===index); if(correct){ feedback('timelineFeedback','Perfect timeline! You travelled from the Indus Valley to the Mughal era in the correct order.','good'); recordWin('timeline'); playTone('good'); } else { const firstWrong=state.selectedTimeline.findIndex((event,index)=>event.order!==index)+1; feedback('timelineFeedback',`Nearly there. Your first out-of-order stop is position ${firstWrong}. Use Undo Last or restart to refine the trail.`,'bad'); playTone('bad'); } }
function resetMemory(){ state.flipped=[]; state.moves=0; state.pairs=0; state.locked=false; state.memoryDeck=shuffle(memoryPairs.flatMap(pair=>[{...pair,id:`${pair.key}-a`},{...pair,id:`${pair.key}-b`}])) ; renderMemory(); feedback('memoryFeedback','Find the matching heritage symbols with as few moves as you can.'); }
function renderMemory(){ $('moveCount').textContent=state.moves; $('pairCount').textContent=`${state.pairs} / 6`; $('bestMoves').textContent=localStorage.getItem('echoesMemoryBest')||'—'; $('memoryGrid').innerHTML=state.memoryDeck.map(card=>`<button type="button" class="memory-card ${state.flipped.includes(card.id)?'flipped':''} ${card.matched?'matched':''}" data-card="${card.id}" aria-label="Hidden heritage card"><span class="memory-inner"><span class="memory-face memory-front">?</span><span class="memory-face memory-back"><span>${card.symbol}</span>${card.label}</span></span></button>`).join(''); document.querySelectorAll('[data-card]').forEach(btn=>btn.onclick=()=>flipCard(btn.dataset.card)); }
function flipCard(id){ const card=state.memoryDeck.find(item=>item.id===id); if(state.locked||card.matched||state.flipped.includes(id)||state.flipped.length===2)return; state.flipped.push(id); renderMemory(); playTone(); if(state.flipped.length!==2)return; state.moves++; const [firstId,secondId]=state.flipped; const first=state.memoryDeck.find(item=>item.id===firstId),second=state.memoryDeck.find(item=>item.id===secondId); if(first.key===second.key){ first.matched=second.matched=true; state.pairs++; state.flipped=[]; setTimeout(()=>{renderMemory(); feedback('memoryFeedback',state.pairs===6?`All pairs found in ${state.moves} moves. You are a Heritage Memory Keeper!`:`Match found: ${first.label}.`,'good');playTone('good'); if(state.pairs===6){const best=Number(localStorage.getItem('echoesMemoryBest')||Infinity);if(state.moves<best)localStorage.setItem('echoesMemoryBest',String(state.moves));recordWin('memory');renderMemory();}},280); } else { state.locked=true; setTimeout(()=>{state.flipped=[];state.locked=false;renderMemory();feedback('memoryFeedback','Not a pair yet — use the symbols and names to make a mental map.','bad');playTone('bad');},760); } }
function switchGame(name){ document.querySelectorAll('.picker-card').forEach(btn=>btn.classList.toggle('active',btn.dataset.game===name)); document.querySelectorAll('.game-panel').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===name)); history.replaceState(null,'',`#${name}`); }
document.querySelectorAll('.picker-card').forEach(btn=>btn.onclick=()=>switchGame(btn.dataset.game)); document.querySelectorAll('[data-restart]').forEach(btn=>btn.onclick=()=>({builder:resetBuilder,timeline:resetTimeline,memory:resetMemory}[btn.dataset.restart])()); $('undoTimeline').onclick=()=>{if(state.selectedTimeline.length){state.selectedTimeline.pop();renderTimeline();feedback('timelineFeedback','Last event removed. Try a different place on the trail.');}}; $('checkTimeline').onclick=checkTimeline; $('soundToggle').onclick=()=>{state.sound=!state.sound;$('soundToggle').textContent=state.sound?'🔊 SOUND':'🔇 MUTED';$('soundToggle').setAttribute('aria-pressed',String(state.sound));};
/* =========================================================
   HERITAGE TRAIL — keyboard + touch 2D exploration, no quiz
========================================================= */
const trailCanvas=$('trailCanvas');
const trailCtx=trailCanvas.getContext('2d');
const trailLevels=[
  {name:'HAMPI BAZAAR', landmark:'Hampi’s stone skyline', text:'Granite boulders, trading streets and temple towers make Hampi feel like a landscape-sized city.', sky:'#31567a', hill:'#6e6551', ground:'#9b6335', accent:'#f7c75b', symbol:'♜', hazards:[510,835,1190,1510,1810], sparks:[280,610,755,1050,1410,1730]},
  {name:'AJANTA RAVINE', landmark:'Ajanta’s painted caves', text:'Follow the river ravine where caves were carved into living rock and made bright with stories.', sky:'#4b5178', hill:'#55544c', ground:'#704f3d', accent:'#f1c47a', symbol:'◒', hazards:[450,740,1070,1450,1710], sparks:[255,580,900,1230,1570,1880]},
  {name:'KONARK DAWN', landmark:'Konark’s sun chariot', text:'A rising sun reveals wheels, horses and the enduring silhouette of a temple built to move.', sky:'#9a5947', hill:'#60413b', ground:'#805139', accent:'#ffe177', symbol:'☀', hazards:[560,870,1260,1530,1830], sparks:[320,660,1010,1175,1460,1760]}
];
const trail={level:0,x:95,y:388,vy:0,hearts:3,score:0,collected:new Set(),running:false,started:false,checkpoint:95,keys:{left:false,right:false},invulnerable:0,frame:0};
const trailFloor=430, trailWidth=2220;
function trailLevel(){return trailLevels[trail.level];}
function setTrailMessage(message,type=''){const node=$('trailMessage');node.textContent=message;node.className=`trail-message game-feedback ${type}`;}
function updateTrailHUD(){const level=trailLevel();$('trailLocation').textContent=level.name;$('trailSparks').textContent=`${trail.collected.size} / ${level.sparks.length}`;$('trailHearts').textContent='♥'.repeat(trail.hearts)+'♡'.repeat(3-trail.hearts);$('trailScore').textContent=String(trail.score).padStart(3,'0');$('viewTitle').textContent=level.landmark;$('viewText').textContent=level.text;$('monumentModel').style.filter=`hue-rotate(${trail.level*33}deg)`;}
function resetTrail(keepIntro=true){trail.level=0;trail.x=95;trail.y=388;trail.vy=0;trail.hearts=3;trail.score=0;trail.collected=new Set();trail.checkpoint=95;trail.running=false;trail.started=false;trail.invulnerable=0;$('trailIntro').classList.toggle('hidden',!keepIntro);$('trailIntro').querySelector('h3').textContent='Bring the story home.';$('trailIntro').querySelector('p:not(.eyebrow)').innerHTML='Find the glowing Memory Sparks before reaching the landmark. Use <b>← →</b> or <b>A D</b> to move and <b>SPACE</b> to jump.';$('trailStart').textContent='BEGIN THE TRAIL →';updateTrailHUD();setTrailMessage('The trail begins at Hampi. Gather every spark to restore the monument’s memory.');drawTrail();}
function startTrail(){if(trail.running)return;trail.running=true;trail.started=true;$('trailIntro').classList.add('hidden');setTrailMessage(`Explore ${trailLevel().name}: collect every Memory Spark, then reach the landmark.`);requestAnimationFrame(trailLoop);}
function jumpTrail(){if(!trail.running)return;if(trail.y>=trailFloor-43){trail.vy=-12;playTone('tap');}}
function hitTrail(){if(trail.invulnerable)return;trail.hearts--;trail.invulnerable=85;trail.x=trail.checkpoint;trail.y=388;trail.vy=-4;playTone('bad');if(trail.hearts<=0){trail.running=false;$('trailIntro').classList.remove('hidden');$('trailIntro').querySelector('h3').textContent='The trail needs another try.';$('trailIntro').querySelector('p:not(.eyebrow)').textContent='Restart from Hampi with three fresh hearts. Every run makes the route easier to remember.';$('trailStart').textContent='TRY THE TRAIL AGAIN →';setTrailMessage('Your explorer ran out of hearts. Restart the trail to continue.','bad');return;}setTrailMessage(`A broken path slowed you down. ${trail.hearts} heart${trail.hearts===1?'':'s'} left — continue from the last safe point.`,'bad');}
function advanceTrail(){const finished=trailLevel();trail.score+=100;playTone('good');if(trail.level===trailLevels.length-1){trail.running=false;recordWin('trail');updateTrailHUD();$('trailIntro').classList.remove('hidden');$('trailIntro').querySelector('.eyebrow').textContent='TRAIL COMPLETE';$('trailIntro').querySelector('h3').textContent='You restored every memory.';$('trailIntro').querySelector('p:not(.eyebrow)').textContent='You crossed Hampi, Ajanta and Konark by movement, curiosity and care. Your route is now part of the Echoes archive.';$('trailStart').textContent='PLAY AGAIN →';setTrailMessage('Trail complete! You are now a Heritage Pathmaker.','good');return;}
trail.level++;trail.x=95;trail.y=388;trail.vy=0;trail.collected=new Set();trail.checkpoint=95;trail.invulnerable=50;updateTrailHUD();setTrailMessage(`${finished.landmark} restored. The route opens toward ${trailLevel().name}.`,'good');}
function drawLandmark(ctx,x,level){ctx.save();ctx.translate(x,trailFloor);ctx.fillStyle='#1a2233';ctx.fillRect(-37,-94,74,94);ctx.fillStyle=level.accent;ctx.fillRect(-33,-90,66,90);ctx.fillStyle='#463029';ctx.beginPath();ctx.arc(0,-102,36,Math.PI,0);ctx.fill();ctx.fillStyle=level.accent;ctx.fillRect(-57,-74,12,74);ctx.fillRect(45,-74,12,74);ctx.fillStyle='#1b2941';ctx.fillRect(-7,-57,14,57);ctx.fillStyle='rgba(255,244,190,.72)';ctx.font='30px serif';ctx.fillText(level.symbol,-13,-116);ctx.restore();}
function drawTrail(){const ctx=trailCtx,level=trailLevel(),camera=Math.max(0,Math.min(trail.x-185,trailWidth-960)),t=trail.frame;const sky=ctx.createLinearGradient(0,0,0,trailFloor);sky.addColorStop(0,level.sky);sky.addColorStop(.76,'#172a46');sky.addColorStop(1,'#0c172b');ctx.fillStyle=sky;ctx.fillRect(0,0,960,540);ctx.fillStyle='rgba(255,232,160,.56)';ctx.beginPath();ctx.arc(760-camera*.04,92,42,0,Math.PI*2);ctx.fill();for(let layer=0;layer<2;layer++){ctx.fillStyle=layer?'rgba(15,30,43,.74)':level.hill;ctx.beginPath();ctx.moveTo(0,trailFloor);for(let x=-100;x<1100;x+=140){const peak=195+((x/140+layer*2)%3)*22;ctx.lineTo(x,peak);ctx.lineTo(x+70,trailFloor);}ctx.lineTo(960,trailFloor);ctx.fill();}
ctx.fillStyle=level.ground;ctx.fillRect(0,trailFloor,960,110);ctx.fillStyle='rgba(255,224,145,.19)';for(let x=-(camera%70);x<960;x+=70){ctx.fillRect(x,trailFloor+19,38,3);ctx.fillRect(x+23,trailFloor+58,33,3);}for(let x=100-(camera*.42%250);x<1000;x+=250){ctx.fillStyle='rgba(16,35,42,.82)';ctx.fillRect(x,trailFloor-86,10,86);ctx.beginPath();ctx.arc(x+5,trailFloor-99,29,0,Math.PI*2);ctx.fill();}
const landmarkX=2050-camera;drawLandmark(ctx,landmarkX,level);level.hazards.forEach(h=>{const x=h-camera;if(x<-35||x>995)return;ctx.fillStyle='#2c1e27';ctx.beginPath();ctx.moveTo(x,trailFloor);ctx.lineTo(x+14,trailFloor-31);ctx.lineTo(x+28,trailFloor);ctx.fill();ctx.strokeStyle='#e5765d';ctx.stroke();});level.sparks.forEach((s,index)=>{if(trail.collected.has(index))return;const x=s-camera,y=367+Math.sin((t+index*18)/15)*7;if(x<-25||x>985)return;ctx.save();ctx.translate(x,y);ctx.rotate(t/35);ctx.fillStyle=level.accent;ctx.shadowColor=level.accent;ctx.shadowBlur=16;ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(7,0);ctx.lineTo(0,12);ctx.lineTo(-7,0);ctx.fill();ctx.restore();});
const px=trail.x-camera;ctx.save();ctx.globalAlpha=trail.invulnerable&&Math.floor(t/5)%2?0.42:1;ctx.fillStyle='#f1ba70';ctx.fillRect(px,trail.y,27,38);ctx.fillStyle='#17233c';ctx.fillRect(px+4,trail.y-13,19,18);ctx.fillStyle='#f7d084';ctx.fillRect(px+7,trail.y-8,13,9);ctx.fillStyle='#f4bf48';ctx.fillRect(px+6,trail.y+38,7,5);ctx.fillRect(px+17,trail.y+38,7,5);ctx.restore();
ctx.fillStyle='rgba(255,255,255,.78)';ctx.font='700 13px Poppins, sans-serif';ctx.fillText(level.name,20,29);ctx.font='12px Poppins, sans-serif';ctx.fillStyle='rgba(236,243,250,.78)';ctx.fillText('MOVE · JUMP · COLLECT · ARRIVE',20,49);if(!trail.started){ctx.fillStyle='rgba(5,11,25,.33)';ctx.fillRect(0,0,960,540);}}
function updateTrail(){if(trail.keys.left)trail.x=Math.max(0,trail.x-5);if(trail.keys.right)trail.x=Math.min(trailWidth-20,trail.x+5);trail.vy+=.65;trail.y+=trail.vy;if(trail.y>trailFloor-42){trail.y=trailFloor-42;trail.vy=0;}if(trail.x>1090)trail.checkpoint=Math.max(trail.checkpoint,1100);const level=trailLevel();level.hazards.forEach(h=>{if(trail.x+27>h&&trail.x<h+28&&trail.y+42>trailFloor-27)hitTrail();});level.sparks.forEach((s,index)=>{if(!trail.collected.has(index)&&Math.abs((trail.x+14)-s)<27&&trail.y+42>330){trail.collected.add(index);trail.score+=15;playTone('good');setTrailMessage(`Memory Spark found! ${trail.collected.size} of ${level.sparks.length} restored.`,'good');updateTrailHUD();}});if(trail.x>2025){if(trail.collected.size===level.sparks.length)advanceTrail();else {trail.x=2010;setTrailMessage(`The landmark is waiting for ${level.sparks.length-trail.collected.size} more Memory Spark${level.sparks.length-trail.collected.size===1?'':'s'}.`,'bad');}}if(trail.invulnerable)trail.invulnerable--;}
function trailLoop(){if(!trail.running){drawTrail();return;}trail.frame++;updateTrail();drawTrail();requestAnimationFrame(trailLoop);}
['keydown','keyup'].forEach(type=>document.addEventListener(type,event=>{const down=type==='keydown';if(['ArrowLeft','a','A'].includes(event.key)){trail.keys.left=down;if(trail.running)event.preventDefault();}if(['ArrowRight','d','D'].includes(event.key)){trail.keys.right=down;if(trail.running)event.preventDefault();}if([' ','ArrowUp','w','W'].includes(event.key)&&down){if(trail.running){event.preventDefault();jumpTrail();}}}));
document.querySelectorAll('[data-trail-control]').forEach(button=>{const control=button.dataset.trailControl;const set=(value)=>{if(control==='jump'&&value)jumpTrail();else if(control!=='jump')trail.keys[control]=value;};button.addEventListener('pointerdown',event=>{event.preventDefault();set(true);});['pointerup','pointercancel','pointerleave'].forEach(name=>button.addEventListener(name,()=>set(false)));});
$('trailStart').onclick=()=>{if(!trail.started)startTrail();else resetTrail(false),startTrail();};$('trailRestart').onclick=()=>{resetTrail(false);startTrail();};
renderWins(); resetBuilder(); resetTimeline(); resetMemory(); resetTrail(); const requested=location.hash.slice(1); if(['trail','builder','timeline','memory'].includes(requested))switchGame(requested);
