const eras = [
  { title:'Indus Valley', date:'c. 2600 BCE · Mohenjo-daro', symbol:'◫', color:'#74d2cd', intro:'You arrive in a carefully planned city of baked-brick homes. Straight streets cross at right angles, and covered drains run beneath your feet.', fact:'Mohenjo-daro had an advanced drainage system—remarkable urban planning for its time.', question:'A sudden monsoon fills the streets. What would best help keep the city healthy?', choices:[['Protect and maintain the covered drains.','Clean water and drainage reduce flooding and disease—an important insight of Indus Valley planners.'],['Block the drains to save water.','That would make flooding worse. The city’s drainage network worked because water could flow away.'],['Move every home outside the city.','The city’s planned infrastructure was the more practical solution.']] },
  { title:'The Mauryan Age', date:'c. 260 BCE · Pataliputra', symbol:'☸', color:'#e7a85c', intro:'You enter Pataliputra, capital of one of India’s largest early empires. Emperor Ashoka has just witnessed the terrible cost of the Kalinga war.', fact:'After Kalinga, Ashoka’s edicts promoted dhamma: ethical conduct, tolerance, and care for people and animals.', question:'You are asked to suggest a new priority for the empire. What do you choose?', choices:[['Build roads, wells, and places of care.','A wise choice. Ashoka’s rule is remembered for public welfare alongside ethical governance.'],['Begin another war to gain more land.','Ashoka’s later inscriptions show a shift away from conquest toward dhamma.'],['Keep every decision secret from the people.','Ashoka used rock and pillar edicts to communicate values across his empire.']] },
  { title:'Vijayanagara', date:'c. 1500 CE · Hampi', symbol:'♜', color:'#e6a7bd', intro:'You walk through Hampi’s bustling bazaars, where traders exchange spices, textiles, horses, and precious stones beneath the watch of towering temples.', fact:'Vijayanagara was a major centre of trade. Its location near the Tungabhadra River supported agriculture, travel, and a thriving city.', question:'A visiting trader asks why Hampi has become so prosperous. What do you explain?', choices:[['River resources, farming, markets, and trade routes work together.','Exactly. Hampi’s prosperity came from a connected system of geography, agriculture, trade, and skilled communities.'],['The city succeeds only because it is isolated.','Hampi was connected to regional and overseas trade, not cut off from it.'],['Its temples alone made every trade decision.','Temples were important cultural and economic centres, but many factors supported the city.']] },
  { title:'Freedom Movement', date:'1942 CE · Across India', symbol:'✊', color:'#f4cf57', intro:'You arrive during a movement shaped by many voices, ideas, and courageous actions. Ordinary people are discussing how a free India should be built.', fact:'India’s freedom struggle included mass movements, debates, writers, workers, students, and leaders with different approaches.', question:'Your group wants to contribute responsibly. Which action best reflects the movement’s democratic spirit?', choices:[['Learn, organise peacefully, and include every community.','A thoughtful choice. Lasting freedom depends on informed participation, inclusion, and shared responsibility.'],['Let only one group speak for everyone.','The journey to democracy required many people and communities to be heard.'],['Ignore the future and focus only on today.','The freedom movement also involved imagining institutions and rights for the future.']] }
];
let unlocked = Number(localStorage.getItem('jttUnlocked') || 0); let memories = JSON.parse(localStorage.getItem('jttMemories') || '[]'); let current = 0; let map; let activeScreen='welcomeScreen';
const places = [
  {name:'Mohenjo-daro', region:'Sindh, Pakistan', coords:[27.3294,68.1386], symbol:'◫', text:'A major Indus Valley city known for its planned streets, brick homes, and advanced drainage.'},
  {name:'Dholavira', region:'Gujarat, India', coords:[23.8861,70.2147], symbol:'◫', text:'An Indus Valley site in Kutch, celebrated for its reservoirs and water-management system.'},
  {name:'Pataliputra', region:'Bihar, India', coords:[25.5941,85.1376], symbol:'☸', text:'The Mauryan capital near modern Patna, associated with Chandragupta Maurya and Ashoka.'},
  {name:'Sanchi', region:'Madhya Pradesh, India', coords:[23.4795,77.7396], symbol:'☸', text:'Home to the Great Stupa, one of India’s most important early Buddhist monuments.', href:'monuments/sanchi.html'},
  {name:'Hampi', region:'Karnataka, India', coords:[15.3350,76.4620], symbol:'♜', text:'The former capital of Vijayanagara, set among boulders and the Tungabhadra River.', href:'hampi.html'},
  {name:'Konark Sun Temple', region:'Odisha, India', coords:[19.8876,86.0945], symbol:'☀', text:'The 13th-century Sun Temple is designed as Surya’s grand stone chariot.', href:'monuments/konark.html'},
  {name:'Jagannath Temple', region:'Puri, Odisha, India', coords:[19.8135,85.8312], symbol:'✺', text:'A living temple tradition at the heart of Puri’s cultural landscape.', href:'monuments/jagannath.html'},
  {name:'Ajanta Caves', region:'Maharashtra, India', coords:[20.5519,75.7033], symbol:'◒', text:'Rock-cut Buddhist caves renowned for paintings and architecture spanning centuries.', href:'monuments/ajanta.html'},
  {name:'Taj Mahal', region:'Agra, Uttar Pradesh', coords:[27.1751,78.0421], symbol:'✦', text:'A 17th-century marble mausoleum commissioned by Shah Jahan.', href:'monuments/taj-mahal.html'},
  {name:'Red Fort', region:'Delhi, India', coords:[28.6562,77.2410], symbol:'⌂', text:'The red-sandstone imperial city at the heart of Mughal Shahjahanabad.', href:'monuments/red-fort.html'},
  {name:'Charminar', region:'Hyderabad, Telangana, India', coords:[17.3616,78.4747], symbol:'✧', text:'Hyderabad’s four-minaret crossroads and a landmark of Deccan heritage.', href:'monuments/charminar.html'},
  {name:'Jallianwala Bagh', region:'Amritsar, Punjab', coords:[31.6200,74.8800], symbol:'✊', text:'A public garden and memorial connected to a defining event in India’s freedom struggle.'},
  {name:'Sabarmati Ashram', region:'Ahmedabad, Gujarat', coords:[23.0607,72.5805], symbol:'✊', text:'Mahatma Gandhi’s ashram, closely associated with the 1930 Salt March.'}
];
const $ = id => document.getElementById(id); const screens=['welcomeScreen','timelineScreen','storyScreen','resultScreen','mapScreen'];
function show(id){ screens.forEach(x=>$(x).classList.toggle('hidden',x!==id)); if(id!=='mapScreen') activeScreen=id; }
function renderTimeline(){ const grid=$('eraGrid'); grid.innerHTML=''; eras.forEach((era,i)=>{ const open=i<=unlocked; const card=document.createElement('button'); card.className='era-card'; card.disabled=!open; card.style.setProperty('--era-color',era.color); card.innerHTML=`<span class="era-number">ERA 0${i+1}</span><span class="era-symbol">${open?era.symbol:'🔒'}</span><div><h3>${era.title}</h3><p>${era.date}</p></div><span class="era-status">${open?(memories[i]?'✓ EXPLORED':'ENTER ERA →'):'LOCKED'}</span>`; if(open) card.onclick=()=>openEra(i); grid.appendChild(card); }); }
function openEra(i){ current=i; const e=eras[i]; $('progressText').textContent=`ERA ${i+1} OF ${eras.length}`; $('progressFill').style.width=`${(i/eras.length)*100}%`; $('storyCard').innerHTML=`<div class="story-era">ERA ${String(i+1).padStart(2,'0')} · ${e.date}</div><h1>${e.title}</h1><p class="story-date">A moment in India's living history</p><p class="story-body">${e.intro}</p><div class="fact-card"><strong>DID YOU KNOW?</strong><br>${e.fact}</div><h3 class="decision-title">Your decision</h3><p class="story-body" style="margin:0 0 15px">${e.question}</p><div class="choices">${e.choices.map((c,n)=>`<button class="choice" data-choice="${n}">${c[0]}</button>`).join('')}</div><div id="outcome" class="outcome"></div><div class="next-row"><button id="nextEra" class="primary-btn next-btn" type="button">${i===eras.length-1?'SEE MY RECORD':'CONTINUE'} <span>→</span></button></div>`; document.querySelectorAll('.choice').forEach(btn=>btn.onclick=()=>choose(Number(btn.dataset.choice))); $('nextEra').onclick=next; show('storyScreen'); window.scrollTo({top:0,behavior:'smooth'}); }
function choose(n){ document.querySelectorAll('.choice').forEach(b=>b.disabled=true); document.querySelector(`[data-choice="${n}"]`).classList.add('selected'); const outcome=$('outcome'); outcome.textContent=eras[current].choices[n][1]; outcome.classList.add('show'); if(!memories[current]) memories[current]={choice:n}; unlocked=Math.max(unlocked,Math.min(current+1,eras.length-1)); localStorage.setItem('jttUnlocked',unlocked); localStorage.setItem('jttMemories',JSON.stringify(memories)); $('progressFill').style.width=`${((current+1)/eras.length)*100}%`; $('nextEra').classList.add('show'); }
function next(){ if(current===eras.length-1){ renderResult(); } else { renderTimeline(); show('timelineScreen'); } }
function renderResult(){ $('resultMessage').textContent='You crossed thousands of years of history and found a shared thread: communities flourish through knowledge, responsibility, connection, and courage.'; $('memoryList').innerHTML=eras.map((e,i)=>`<div class="memory"><span>${e.symbol}</span><strong>${e.title}</strong> — ${memories[i]?'Your decision has been recorded.':'Awaiting your visit.'}</div>`).join(''); show('resultScreen'); }
function satelliteUrl(coords,zoom){ return `https://www.google.com/maps/@?api=1&map_action=map&center=${encodeURIComponent(coords.join(','))}&zoom=${zoom}&basemap=satellite`; }
function selectPlace(place){ const url=satelliteUrl(place.coords,15); $('placePanel').innerHTML=`<div class="place-symbol">${place.symbol}</div><p class="place-region">${place.region}</p><h3>${place.name}</h3><p>${place.text}</p><a class="map-btn" href="${url}" target="_blank" rel="noopener" style="display:inline-block;margin-top:14px;text-decoration:none">OPEN SATELLITE VIEW ↗</a>${place.href?`<a class="map-btn" href="${place.href}" style="display:inline-block;margin:10px 0 0 8px;text-decoration:none">OPEN STORY PAGE →</a>`:''}`; const selected=$('satelliteSelectedName'), selectedLink=$('satelliteSelectedLink'); if(selected&&selectedLink){selected.textContent=`SELECTED: ${place.name.toUpperCase()}`;selectedLink.href=url;selectedLink.hidden=false;} }
function createMap(){ if(map) return; map=true; const mapNode=$('heritageMap'); mapNode.className='satellite-launch'; mapNode.innerHTML=`<div><div class="satellite-orbit" aria-hidden="true">◉</div><p class="eyebrow">LIVE IMAGERY · GOOGLE MAPS</p><h3>See Bharat from above.</h3><p>This project opens Google Maps in Satellite mode, where you can zoom, pan and see current real-world imagery without a map API key.</p><a id="indiaSatelliteLink" class="satellite-live-link" href="${satelliteUrl([22.7,79.2],5)}" target="_blank" rel="noopener">OPEN INDIA SATELLITE MAP ↗</a><p id="satelliteSelectedName" class="satellite-selected">SELECT A HERITAGE STOP BELOW</p><a id="satelliteSelectedLink" class="satellite-mini-link" href="#" target="_blank" rel="noopener" hidden>OPEN SELECTED SATELLITE VIEW ↗</a></div>`; $('placeChips').innerHTML=places.map((p,i)=>`<button class="place-chip" data-place="${i}">${p.symbol} ${p.name}</button>`).join(''); document.querySelectorAll('.place-chip').forEach(button=>button.onclick=()=>selectPlace(places[Number(button.dataset.place)])); }
$('beginJourney').onclick=()=>{renderTimeline();show('timelineScreen');}; $('backToTimeline').onclick=()=>{renderTimeline();show('timelineScreen');}; $('travelAgain').onclick=()=>{renderTimeline();show('timelineScreen');}; $('openMap').onclick=()=>{show('mapScreen'); createMap();}; $('mapBack').onclick=()=>show(activeScreen); $('resetJourney').onclick=()=>{ if(confirm('Start the Journey Through Time again? Your saved progress will be cleared.')) { unlocked=0; memories=[]; localStorage.removeItem('jttUnlocked'); localStorage.removeItem('jttMemories'); renderTimeline(); show('welcomeScreen'); }}; if(location.hash==='#map'){ show('mapScreen'); createMap(); }
